apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: script
spec:
  taskRef:
    name: script 

    ---
    apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: maven
spec:
  taskRef:
    name: maven